version: "3.8"

services:
   db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - '5432:5432'
   pg:
      image: 'dpage/pgadmin4'
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports: 
        - '80:80'
      depends_on: 
        - db