version: "3.8"

services:
   postgresql:
      image: postgres
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: lynx
      ports:
        - 5432:5432
   app:
      image: 'app'
      ports: 
        - 1993:1993